# Generated by Django 4.1.1 on 2022-10-06 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0003_autos_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='autos',
            name='descripcion',
            field=models.TextField(blank=True, max_length=240, null=True),
        ),
    ]
