# Generated by Django 4.1.1 on 2022-10-08 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0004_autos_descripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autos',
            old_name='año_fab',
            new_name='año_de_fabricacion',
        ),
    ]
