# Generated by Django 4.1.1 on 2022-10-08 16:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0005_rename_año_fab_autos_año_de_fabricacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='autos',
            name='fecha_de_edicion',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
