# Generated by Django 4.1.1 on 2022-10-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0006_autos_fecha_de_edicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='autos',
            name='combustible',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='autos',
            name='motorizacion',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='autos',
            name='version',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
